src/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static


# nom des urls 
app_name = 'accounts'

urlpatterns = [
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
]

src/garantix_config/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from garantix_config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('warranty.urls', namespace='warranty')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/warranty/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from warranty import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'warranty'

urlpatterns = [
  path('', views.HomeView.as_view(), name='home'), 
  path('warranty/<int:pk>/', views.WarrantyDetailView.as_view(), name='warranty_detail'), 
  path('update/<int:pk>/', views.WarrantyUpdateView.as_view(), name='warranty_update'), 
  path('delete/<int:pk>/', views.WarrantyDeleteView.as_view(), name='warranty_delete'), 
  path('warranties/', views.WarrantiesListView.as_view(), name='warranties_list'),
  path('create/', views.WarrantyCreateView.as_view(), name='warranty_create'), 
]

src/templates/blocks/footer.html
<footer>
  <!-- copyright + cuurent year -->
  <div style="margin-bottom: 0.5rem; color:black;">&copy; {% now "Y" %} Garantix tous droits réservés</div>
  <!-- links to another page -->
  <sl-button variant="text" href="#" target="_blank" class="footer-link">Mentions légales</sl-button>
  <sl-button variant="text" href="#" target="_blank" class="footer-link">Politique de confidentialité</sl-button>
  <sl-button variant="text" href="#" target="_blank" class="footer-link">Contact</sl-button>
</footer>

src/templates/blocks/header.html
{% load static %}
<header class="navbar">
  <div class="nav-brand">Garantix</div>
  
  <!-- Desktop menu -->
  <nav class="nav-desktop">
    <sl-button variant="text" href="{% url 'warranty:home' %}">
       <sl-icon name="house-door-fill" label="accueil" class="icon-medium menu-icon"></sl-icon>
       Accueil
    </sl-button>
    {% if user.is_authenticated %}
      <sl-button variant="text" href="{% url 'warranty:warranties_list' %}">
        <sl-icon name="file-earmark-fill" label="garanties" class="icon-medium menu-icon"></sl-icon>
        Mes garanties
      </sl-button>
      <sl-button variant="text" class="login-btn-navbar" href="{% url 'accounts:logout' %}">
        <sl-icon name="power" label="déconnexion" class="icon-medium menu-icon"></sl-icon>
        Se déconnecter
      </sl-button>
    {% else %}
      <sl-button href="{% url 'accounts:login' %}" class="login-btn-navbar" size="medium" title="Se connecter">
        <sl-icon name="person-fill" label="connexion" class="icon-medium menu-icon"></sl-icon>
          Se connecter
        </sl-button>
    {% endif %}
  </nav>
  
  <!-- Mobile menu button -->
  <sl-button class="nav-mobile-toggle" variant="text" id="mobile-menu-btn">
    <sl-icon name="list"></sl-icon>
  </sl-button>
</header>

<!-- Mobile menu (caché par défaut) -->
<nav class="nav-mobile" id="mobile-menu">
  <sl-button variant="text" href="{% url 'warranty:home' %}" title="Accueil">
    <sl-icon name="house-door-fill" label="accueil" class="icon-small menu-icon" style="color:black;"></sl-icon>
    Accueil
  </sl-button>
  {% if request.user.is_authenticated %}
  <sl-button variant="text" href="{% url 'warranty:warranties_list' %}" title="Mes garanties">
    <sl-icon name="file-earmark-fill" label="garanties" class="icon-small menu-icon" style="color:black;"></sl-icon>
    Mes garanties
  </sl-button>
  <sl-button variant="primary" class="login-btn-navbar">
    <sl-icon name="person-fill" label="deconnexion" class="icon-small menu-icon"></sl-icon>
    Se déconnecter
  </sl-button>
  {% else %}
  <sl-button variant="primary" class="login-btn-navbar" href="/admin/"  title="Se déconnecter">
    <sl-icon name="person-fill" label="connexion" class="icon-small menu-icon"></sl-icon>
    Se connecter
  </sl-button>
  {% endif %}
</nav>


<script>

  document.addEventListener('DOMContentLoaded', () => {
    const mobileMenuBtn = document.getElementById('mobile-menu-btn');
    const mobileMenu = document.getElementById('mobile-menu');
  
    mobileMenuBtn.addEventListener('click', () => {
      mobileMenu.classList.toggle('open');
      // icon burger menu 
      const icon = mobileMenuBtn.querySelector('sl-icon');
      if (mobileMenu.classList.contains('open')) {
        icon.name = 'x';
      } else {
        icon.name = 'list';
      }
    });
  
    const mobileLinks = mobileMenu.querySelectorAll('sl-button');

    mobileLinks.forEach(link => {
      link.addEventListener('click', () => {
        mobileMenu.classList.remove('open');
        mobileMenuBtn.querySelector('sl-icon').name = 'list';
      });
    });
  });
</script>