src/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static


# nom des urls 
app_name = 'accounts'

urlpatterns = [
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
]

src/garantix_config/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from garantix_config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('warranty.urls', namespace='warranty')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/warranty/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from warranty import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'warranty'

urlpatterns = [
  path('', views.HomeView.as_view(), name='home'), 
  path('warranty/<int:pk>/', views.WarrantyDetailView.as_view(), name='warranty_detail'), 
  path('update/<int:pk>/', views.WarrantyUpdateView.as_view(), name='warranty_update'), 
  path('delete/<int:pk>/', views.WarrantyDeleteView.as_view(), name='warranty_delete'), 
  path('warranties/', views.WarrantiesListView.as_view(), name='warranties_list'),
  path('create/', views.WarrantyCreateView.as_view(), name='warranty_create'), 
]

src/warranty/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils import timezone
from datetime import timedelta


class Warranty(models.Model): 
    product_name = models.CharField(max_length=200, verbose_name="Nom du produit")
    brand = models.CharField(max_length=150, verbose_name="Nom de la marque")
    purchase_date = models.DateField(verbose_name="Date d'achat")
    warranty_duration_months = models.PositiveIntegerField(verbose_name="Durée de garantie (en mois)")
    vendor = models.CharField(max_length=100, blank=True, null=True, verbose_name="Fournisseur")
    imageReceipt = models.ImageField(upload_to='receipts/', blank=True, null=True, verbose_name="Image du reçu")
    notes = models.TextField(blank=True, null=True, verbose_name="Notes")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Crée le")

    # Warranty.objects.all() return les résultats triés par ordre alphabétique du nom
    class Meta:
        ordering = ['product_name', 'brand'] # tri par nom d'abord puis par marque si même nom 
        verbose_name = "Garanties"

    # redirection apres ajout d'une garantie 
    def get_absolute_url(self):
        return reverse('warranty:warranties_list') 
    
    @property
    def warranty_expiry_date(self): 
        return self.purchase_date + timedelta(days=self.warranty_duration_months * 30)
    
    def __str__(self):
        """method to string"""
        return f"{self.product_name} {self.brand}"

src/warranty/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Warranty


class CustomUserCreationForm(UserCreationForm):
    username = forms.EmailField(label="Email", required=True)

    class Meta:
        model = User
        fields = ("username", "password1", "password2")


class WarrantyForm(forms.ModelForm):
    class Meta:
        model = Warranty
        fields = ["product_name", "brand", "purchase_date", "warranty_duration_months", "vendor", "imageReceipt", "notes"]

src/warranty/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.conf import settings
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from warranty.models import Warranty
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import redirect
from django.views import View
from django.db.models import Q
from warranty.mixins import ContextDataMixin, WarrantySearchMixin
from .forms import WarrantyForm

class HomeView(TemplateView): 
    """ 
    Accueil 
    """
    template_name = "warranty/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['media_url'] = settings.MEDIA_URL
        return context


@method_decorator(login_required, name="dispatch")
class WarrantiesListView(ContextDataMixin, WarrantySearchMixin, ListView): 
    """
    Liste des garanties 
    """
    model = Warranty
    context_object_name = "warranties" # variable in template
    template_name = "warranty/warranties_list.html"
    fields = ["product_name", "brand", "purchase_date", "warranty_duration_months", "vendor", "imageReceipt", "notes", "created_at", ]


@method_decorator(login_required, name="dispatch")
class WarrantyDetailView(DetailView):
    """ Page Détail de la garantie """
    model = Warranty
    context_object_name = "warranty"
    template_name = "warranty/warranty_detail.html"
    fields = ["product_name", "brand", "purchase_date", "warranty_duration_months", "vendor", "imageReceipt", "notes", "created_at", ]

    # def get_queryset(self):
    #     """ne retourne que les garanties de l'utilisateur connecté"""
    #     return Warranty.objects.filter(user=self.request.user)


@method_decorator(login_required, name="dispatch")
class WarrantyCreateView(CreateView): 
    """ Page Créer une nouvelle garantie """
    model = Warranty
    template_name = "warranty/warranty_create.html"
    fields = ["product_name", "brand", "purchase_date", "warranty_duration_months", "vendor", "imageReceipt", "notes", ]


@method_decorator(login_required, name="dispatch")
class WarrantyUpdateView(UpdateView):
    """ Page Modifier une garantie """
    model = Warranty
    template_name = "warranty/warranty_update.html"
    fields = ["product_name", "brand", "purchase_date", "warranty_duration_months", "vendor", "imageReceipt", "notes", ]
    # success_url = reverse_lazy('warranty:warranties_list')
        
    def post(self, request, *args, **kwargs):
        """Surcharge pour forcer la prise en compte des fichiers"""
        print("📁 REQUEST.FILES:", request.FILES)
        print("📝 REQUEST.POST:", request.POST)
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        print("✅ Form valide!")
        print("📁 FILES dans form:", self.request.FILES)
        
        # Si un nouveau fichier est uploadé, l'assigner manuellement
        if 'imageReceipt' in self.request.FILES:
            form.instance.imageReceipt = self.request.FILES['imageReceipt']
            print("🖼️ Nouvelle image assignée!")
        
        return super().form_valid(form)
    
        
@method_decorator(login_required, name="dispatch")
class WarrantyDeleteView(DeleteView): 
    """ Page Supprimer une garantie """
    model = Warranty
    context_object_name = "warranty"
    success_url = reverse_lazy("warranty:home")

src/warranty/templates/warranty/Home.html
{% extends "base.html" %} 
{% load static %}

{% block title %}
  <title>Garantix - Accueil</title>
{% endblock title %} 

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}


{% block content %}

  <!-- section hero (slogan) -->
  <section id="hero">
    <article>
      {% include 'partials/_messages.html' %}

      <h1>Bienvenue sur Garantix</h1>
      
      <p>Centralisez vos garanties. Ne perdez plus un seul reçu.</p>
      {% if user.is_authenticated %}
        <sl-button href="{% url 'accounts:logout' %}" class="btn btn-primary" size="medium">
          Se déconnecter
        </sl-button>
      {% else %}
        <sl-button href="{% url 'accounts:login' %}" class="btn btn-primary" size="medium">
          Se connecter
        </sl-button>
        <sl-button href="{% url 'accounts:signup' %}" class="btn btn-white" size="medium">
          Créer un compte
        </sl-button>
      {% endif %}
    </article>
  </section>

  <!-- section features -->
  <section id="features" class="contain">
    <article>
      <div class="card-group">
        <sl-card class="custom-card">
          <sl-icon name="archive" class="custom-card-icon"></sl-icon>
          <h3>Stockez vos garanties</h3>
          <p>Centralisez tous vos documents et reçus en un seul endroit, accessible partout.</p>
        </sl-card>

        <sl-card class="custom-card">
          <sl-icon name="search" class="custom-card-icon"></sl-icon>
          <h3>Retrouvez facilement</h3>
          <p>Recherchez vos produits et garanties rapidement grâce à notre interface intuitive.</p>
        </sl-card>

        <sl-card class="custom-card">
          <sl-icon name="cloud" class="custom-card-icon"></sl-icon>
          <h3>Accès sécurisé</h3>
          <p>Vos données sont sauvegardées en toute sécurité.</p>
        </sl-card>

         <sl-card class="custom-card">
          <sl-icon name="alarm" class="custom-card-icon"></sl-icon>
          <h3>Alertes avant expiration</h3>
          <p>Recevez des notifications pour ne jamais oublier une garantie importante.</p>
        </sl-card>
      </div>
    </article>
  </section>

  <!-- section mockup  -->
  <section id="mockup" class="contain">
    <div class="image-grid">
      <div class="grid-item">
        <img src="{% static 'images/logo_blue1.png' %}" 
            alt="Dashboard example" class="grid-img"> 
      </div>
      <div class="grid-item">
        <img src="{% static 'images/logo_black1.png' %}" 
            alt="Dashboard example" class="grid-img">
      </div>
      <div class="grid-item">
        <img src="{% static 'images/logo_black2.png' %}" 
            alt="Dashboard example" class="grid-img">
      </div>
    </div>
  </section> 

  <!-- section Call to action -->
  <section id="cta" class="contain">
    <article>
      <h2>Rejoignez Garantix dès aujourd'hui</h2>
      <p>Ne perdez plus vos garanties et facilitez votre suivi.</p>
      <sl-button class="btn btn-white" size="medium">S'inscrire gratuitement</sl-button>
    </article>
  </section>

  <!-- section testimonials -->
  <section id="testimonials" class="contain">
    <div>
      <h2>Témoignages</h2>
      <div class="testimonials-card-group">
        <sl-card class="testimonial-card">
          <blockquote>« Grâce à Garantix, j’ai pu retrouver ma garantie en quelques secondes. »</blockquote>
          <div slot="footer">
            <sl-rating value="4.5" readonly></sl-rating>
            <span>— Marie, cliente</span>
          </div>
        </sl-card>

        <sl-card class="testimonial-card">
          <blockquote>« Les rappels d’expiration sont super pratiques. Je recommande Garantix. »</blockquote>
          <div slot="footer">
            <sl-rating value="5" readonly></sl-rating>
            <span>— Julien, client</span>
          </div>
        </sl-card>

        <sl-card class="testimonial-card">
          <blockquote>« Enfin une solution simple pour centraliser l'ensemble de mes garanties ! »</blockquote>
          <div slot="footer">
            <sl-rating value="4.5" readonly></sl-rating>
            <span>— Sarah, cliente</span>
          </div>
        </sl-card>
      </div>
    </div>
  </section>


{% endblock content %}

src/warranty/templates/warranty/home.html
{% extends "base.html" %} 
{% load static %}

{% block title %}
  <title>Garantix - Accueil</title>
{% endblock title %} 

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}


{% block content %}

  <!-- section hero (slogan) -->
  <section id="hero">
    <article>
      {% include 'partials/_messages.html' %}

      <h1>Bienvenue sur Garantix</h1>
      
      <p>Centralisez vos garanties. Ne perdez plus un seul reçu.</p>
      {% if user.is_authenticated %}
        <sl-button href="{% url 'accounts:logout' %}" class="btn btn-primary" size="medium">
          Se déconnecter
        </sl-button>
      {% else %}
        <sl-button href="{% url 'accounts:login' %}" class="btn btn-primary" size="medium">
          Se connecter
        </sl-button>
        <sl-button href="{% url 'accounts:signup' %}" class="btn btn-white" size="medium">
          Créer un compte
        </sl-button>
      {% endif %}
    </article>
  </section>

  <!-- section features -->
  <section id="features" class="contain">
    <article>
      <div class="card-group">
        <sl-card class="custom-card">
          <sl-icon name="archive" class="custom-card-icon"></sl-icon>
          <h3>Stockez vos garanties</h3>
          <p>Centralisez tous vos documents et reçus en un seul endroit, accessible partout.</p>
        </sl-card>

        <sl-card class="custom-card">
          <sl-icon name="search" class="custom-card-icon"></sl-icon>
          <h3>Retrouvez facilement</h3>
          <p>Recherchez vos produits et garanties rapidement grâce à notre interface intuitive.</p>
        </sl-card>

        <sl-card class="custom-card">
          <sl-icon name="cloud" class="custom-card-icon"></sl-icon>
          <h3>Accès sécurisé</h3>
          <p>Vos données sont sauvegardées en toute sécurité.</p>
        </sl-card>

         <sl-card class="custom-card">
          <sl-icon name="alarm" class="custom-card-icon"></sl-icon>
          <h3>Alertes avant expiration</h3>
          <p>Recevez des notifications pour ne jamais oublier une garantie importante.</p>
        </sl-card>
      </div>
    </article>
  </section>

  <!-- section mockup  -->
  <section id="mockup" class="contain">
    <div class="image-grid">
      <div class="grid-item">
        <img src="{% static 'images/logo_blue1.png' %}" 
            alt="Dashboard example" class="grid-img"> 
      </div>
      <div class="grid-item">
        <img src="{% static 'images/logo_black1.png' %}" 
            alt="Dashboard example" class="grid-img">
      </div>
      <div class="grid-item">
        <img src="{% static 'images/logo_black2.png' %}" 
            alt="Dashboard example" class="grid-img">
      </div>
    </div>
  </section> 

  <!-- section Call to action -->
  <section id="cta" class="contain">
    <article>
      <h2>Rejoignez Garantix dès aujourd'hui</h2>
      <p>Ne perdez plus vos garanties et facilitez votre suivi.</p>
      <sl-button class="btn btn-white" size="medium">S'inscrire gratuitement</sl-button>
    </article>
  </section>

  <!-- section testimonials -->
  <section id="testimonials" class="contain">
    <div>
      <h2>Témoignages</h2>
      <div class="testimonials-card-group">
        <sl-card class="testimonial-card">
          <blockquote>« Grâce à Garantix, j’ai pu retrouver ma garantie en quelques secondes. »</blockquote>
          <div slot="footer">
            <sl-rating value="4.5" readonly></sl-rating>
            <span>— Marie, cliente</span>
          </div>
        </sl-card>

        <sl-card class="testimonial-card">
          <blockquote>« Les rappels d’expiration sont super pratiques. Je recommande Garantix. »</blockquote>
          <div slot="footer">
            <sl-rating value="5" readonly></sl-rating>
            <span>— Julien, client</span>
          </div>
        </sl-card>

        <sl-card class="testimonial-card">
          <blockquote>« Enfin une solution simple pour centraliser l'ensemble de mes garanties ! »</blockquote>
          <div slot="footer">
            <sl-rating value="4.5" readonly></sl-rating>
            <span>— Sarah, cliente</span>
          </div>
        </sl-card>
      </div>
    </div>
  </section>


{% endblock content %}

src/warranty/templates/warranty/warranties_list.html
{% extends "base.html" %} {% block title %}
    <title>Liste des garanties</title>
{% endblock %} 


{% block content %}

    <section class="section-message">
        {% include 'partials/_messages.html' %}
    </section>

    <!-- Searchbar section -->
    <section id="search">
        <h2 id="search-warranty-title">Rechercher une garantie</h2>

        <form method="get" class="searchbar">
            <sl-input 
                name="search" 
                placeholder="Saisir le nom d'un produit ou marque" 
                size="large" 
                clearable 
                value="{{ request.GET.search }}">
            </sl-input>
            <sl-button type="submit" variant="default" size="large">
                <sl-icon name="search" label="Rechercher"></sl-icon>
            </sl-button>
        </form>
    </section>

    <sl-divider></sl-divider>

    <!-- List warranties section -->
    <section id="warranties" class="container">

        <!-- total warranties found -->
        <div>
            <p>{{ warranties|length }} garanties trouvées</p>
        </div>
       
        <div class="title">
            <h1>Mes garanties</h1>

            <!-- Add Warranty button -->
            <sl-tooltip content="Ajouter une garantie">
                <sl-button size="medium" circle class="icon-btn" variant="neutral" outline href={% url 'warranty:warranty_create' %}>
                    <sl-icon name="plus-lg" label="plus-lg" class="icon-medium"></sl-icon>
                </sl-button>
            </sl-tooltip>
        </div>
            
        <!-- List warranties -->
        <article id="warranties_list">
        {% for warranty in warranties %}
            <!-- card produit -->
            <sl-card class="card-header">
                <div slot="header" class="card-header-title">
                    <h2 class="truncate-title">{{ warranty.product_name }}</h2>
                    <h3>{{ warranty.brand }}</h3>
                </div>
                
                <div>
                    <ul>
                        <li>Date d'achat : {{ warranty.purchase_date|date:"d/m/Y" }} </li>
                        <li>Garantie : {{ warranty.warranty_duration_months }} mois</li>
                    </ul>

                    <div class="btns-action">
                        <form action="">
                            <!-- Detail Warranty link -->
                            <sl-button size="medium" circle class="icon-btn"  variant="neutral" outline href={% url 'warranty:warranty_detail' warranty.pk %}>
                                <sl-icon name="file-earmark-fill" label="garantie" class="icon-medium" style="color:black;"></sl-icon>
                            </sl-button>
                        </form>
                        <!-- Action buttons -->
                        <div class="action-btns">
                            {% if request.user.is_authenticated %}
                                <!-- Edit button -->
                                <sl-button size="medium" circle class="icon-btn"  variant="warning" outline href="{% url 'warranty:warranty_update' warranty.pk %}">
                                    <sl-icon name="pencil-square" label="modifier" class="icon-medium"></sl-icon>
                                </sl-button>
                                <!-- Delete button -->
                                <sl-button size="medium" circle class="icon-btn" variant="danger" outline href="{% url 'warranty:warranty_delete' warranty.pk %}">
                                    <sl-icon name="trash2" label="supprimer" class="icon-medium"></sl-icon>
                                </sl-button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </sl-card>
            {% empty %}
            Aucune garantie trouvée pour votre recherche</p>
        {% endfor %}
        </article>
    </section>
{% endblock %}

src/warranty/templates/warranty/warranty_confirm_delete.html
{% extends "base.html" %} {% block title %}
    <title>Supprimer une garantie</title>
{% endblock %} 


{% block content %}

    <form action="" method="POST">
    {% csrf_token %}
        <p>Etes-vous sûr de vouloir supprimer la garantie <b>{{ warranty.product_name }}</b> ?</p>
        <input type="submit" value="Oui supprimer">
    </form>

{% endblock %} 

src/warranty/templates/warranty/warranty_create.html
{% extends 'base.html' %} 


{% block title %}
    <title>Ajouter une garantie</title>
{% endblock %} 


{% block content %}
<section class="title">
    <h1>Ajouter une garantie</h1>
</section>


<!-- form section create -->
<section class="form-container">

    <sl-card class="form-card">

    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

     <div class="form-grid">
        <!-- Colonne de gauche -->
        <div class="form-column">
          <sl-input name="product_name" placeholder="Nom du produit" clearable value="{{ form.product_name.value|default:'' }}" required></sl-input>
          <sl-input name="purchase_date" type="date" placeholder="Date d'achat" value="{{ form.purchase_date.value|default:'' }}" required></sl-input>
          <sl-input name="vendor" placeholder="Revendeur" clearable value="{{ form.vendor.value|default:'' }}"></sl-input>
        </div>

        <!-- Colonne de droite -->
        <div class="form-column">
          <sl-input name="brand" placeholder="Marque" clearable value="{{ form.brand.value|default:'' }}" required></sl-input>
          <sl-input name="warranty_duration_months" type="number" placeholder="Durée de garantie (mois)" value="{{ form.warranty_duration_months.value|default:'' }}" required></sl-input>
          <sl-input name="imageReceipt" type="file" placeholder="Image du reçu"></sl-input>
        </div>
      </div>

      <!-- Notes (pleine largeur) -->
      <sl-textarea name="notes" placeholder="Notes sur le produit" rows="4" help-text="Ajoutez une note sur la garantie">{{ form.notes.value|default:'' }}</sl-textarea>
      
      <!-- Bouton -->
      <div class="submit-container" >
        <sl-button variant="secondary"><a href="{% url 'warranty:warranties_list' %}">Retour à la liste</a></sl-button>
        <sl-button type="submit" variant="primary">Ajouter la garantie</sl-button>
      </div>
      
    </form>

      </sl-card>
</section>

{% endblock %}

src/warranty/templates/warranty/warranty_detail.html
{% extends "base.html" %} 


{% block title %}
    <title>{{ warranty.product_name }}</title>
{% endblock %} 


{% block content %}

<!-- Detail warranty section -->
<section id="warranty-section">
  <article class="warranty-detail">
    <header class="warranty-header">
        <h2>{{ warranty.product_name }}</h2>
        <h3>{{ warranty.brand }}</h3>
    </header>

    <div class="warranty-body">
        <div class="warranty-text">
            <p><b>Date d'achat:</b> {{ warranty.purchase_date|date:'j F Y' }}</p>
            <p><b>Durée de garantie:</b> {{ warranty.warranty_duration_months }} mois</p>
            <p><b>Revendeur:</b> {{ warranty.vendor }}</p>
            <p><b>Notes:</b> {{ warranty.notes|safe|linebreaks }}</p>
            <p><b>Enregistré le </b> {{ warranty.created_at|date:'j F Y' }}</p>
            
        </div>
        <!-- Image of receipt -->
        {% if warranty.imageReceipt %}
        <div class="warranty-image">
            <img 
                src="{{ warranty.imageReceipt.url }}" 
                alt="photo du ticket de caisse de {{ warranty.product_name }}" 
                width="200">
        </div>
        {% else %}
            <p></p>
        {% endif %}
        
    </div>
</article>

</section>

{% endblock %}

src/warranty/templates/warranty/warranty_update.html
{% extends 'base.html' %} 
{% block title %} 
    <title>Modifier une garantie</title> 
{% endblock title %} 


{% block content %}

<!-- Title section -->
<section class="title">
    <h1>Modifier une garantie</h1>
</section>


<!-- form section create -->
<section class="form-container">
    <sl-card class="form-card">
        <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

            <div class="form-grid">
                <!-- Colonne de gauche -->
                <div class="form-column">
                    <sl-input name="product_name" placeholder="Nom du produit" clearable value="{{ warranty.product_name }}" required></sl-input>
                    <sl-input name="purchase_date" type="date" placeholder="Date d'achat" value="{{ warranty.purchase_date|date:'Y-m-d' }}" required></sl-input>
                    <sl-input name="vendor" placeholder="Revendeur" clearable value="{{ warranty.vendor }}"></sl-input>
                </div>

                <!-- Colonne de droite -->
                <div class="form-column">
                    <sl-input name="brand" placeholder="Marque" clearable value="{{ warranty.brand }}" required></sl-input>
                    <sl-input name="warranty_duration_months" type="number" placeholder="Durée de garantie (mois)" value="{{ warranty.warranty_duration_months }}" required></sl-input>
                    <!-- img -->
                    <sl-input name="imageReceipt" type="file" placeholder="Image du reçu"></sl-input>
                </div>
            </div>

            <!-- Notes (pleine largeur) -->
            <sl-textarea name="notes" placeholder="Notes sur le produit" rows="4" help-text="Ajoutez une note sur la garantie">{{ warranty.notes }}</sl-textarea>

            <!-- Bouton -->
            <div class="submit-container">
                <sl-button type="button" variant="secondary"><a href="{% url 'warranty:warranties_list' %}">Retour à la liste</a></sl-button>
                <sl-button type="submit" variant="primary">Modifier la garantie</sl-button>
            </div>
            
        </form>
    </sl-card>
</section>

{% endblock content %}